import os

# Use /var/data/data.json if it exists, otherwise use local.json
if os.path.exists("/var/data/data.json"):
    JSON_FILE_PATH = "/var/data/data.json"
else:
    JSON_FILE_PATH = "local.json"

TEAMS_ALIVE_MASK = {
    "Memphis": 0,
    "New Mexico": 1,
    "Purdue": 1,
    "Lipscomb": 0,
    "Texas": 0,
    "UC San Diego": 0,
    "Creighton": 1,
    "Marquette": 0,
    "SIUE": 0,
    "Omaha": 0,
    "Yale": 0,
    "Wisconsin": 1,
    "Drake": 1,
    "Norfolk St.": 0,
    "Duke": 1,
    "Colo. St.": 1,
    "Auburn": 1,
    "Alabama": 1,
    "Miss. St.": 0,
    "Bryant": 0,
    "St. John's": 1,
    "Texas Tech": 1,
    "Tennessee": 1,
    "Florida": 1,
    "Kansas": 0,
    "Xavier": 0,
    "Iowa St.": 1,
    "Gonzaga": 1,
    "North Carolina": 0,
    "American": 0,
    "Vanderbilt": 0,
    "Utah St.": 0,
    "Oklahoma": 0,
    "Michigan": 1,
    "Arizona": 1,
    "Clemson": 0,
    "Louisville": 0,
    "Kentucky": 1,
    "Maryland": 1,
    "BYU": 1,
    "Baylor": 1,
    "Texas A&M": 1,
    "Arkansas": 1,
    "Georgia": 0,
    "Houston": 1,
    "VCU": 0,
    "Alabama St.": 0,
    "Robert Morris": 0,
    "Illinois": 1,
    "Ole Miss": 1,
    "Grand Canyon": 0,
    "UConn": 1,
    "UNCW": 0,
    "High Point": 0,
    "Saint Mary's": 1,
    "Troy": 0,
    "Wofford": 0,
    "Oregon": 1,
    "Missouri": 0,
    "Akron": 0,
    "UCLA": 1,
    "Liberty": 0,
    "Montana": 0,
    "San Diego St.": 0,
    "St. Fran.-Pa.": 0,
    "Mt St Mary's": 0,
    "McNeese": 1,
    "Mich. St.": 1
}