import os

# Use /var/data/data.json if it exists, otherwise use local.json
if os.path.exists("/var/data/data.json"):
    JSON_FILE_PATH = "/var/data/data.json"
else:
    JSON_FILE_PATH = "local.json"

TEAMS_ALIVE_MASK = {
    "Memphis": 0,
    "New Mexico": 0,
    "Purdue": 1,
    "Lipscomb": 0,
    "Texas": 0,
    "UC San Diego": 0,
    "Creighton": 0,
    "Marquette": 0,
    "SIUE": 0,
    "Omaha": 0,
    "Yale": 0,
    "Wisconsin": 0,
    "Drake": 0,
    "Norfolk St.": 0,
    "Duke": 1,
    "Colo. St.": 0,
    "Auburn": 1,
    "Alabama": 1,
    "Miss. St.": 0,
    "Bryant": 0,
    "St. John's": 0,
    "Texas Tech": 1,
    "Tennessee": 1,
    "Florida": 1,
    "Kansas": 0,
    "Xavier": 0,
    "Iowa St.": 0,
    "Gonzaga": 0,
    "North Carolina": 0,
    "American": 0,
    "Vanderbilt": 0,
    "Utah St.": 0,
    "Oklahoma": 0,
    "Michigan": 1,
    "Arizona": 1,
    "Clemson": 0,
    "Louisville": 0,
    "Kentucky": 1,
    "Maryland": 1,
    "BYU": 1,
    "Baylor": 0,
    "Texas A&M": 0,
    "Arkansas": 1,
    "Georgia": 0,
    "Houston": 1,
    "VCU": 0,
    "Alabama St.": 0,
    "Robert Morris": 0,
    "Illinois": 0,
    "Ole Miss": 1,
    "Grand Canyon": 0,
    "UConn": 0,
    "UNCW": 0,
    "High Point": 0,
    "Saint Mary's": 0,
    "Troy": 0,
    "Wofford": 0,
    "Oregon": 0,
    "Missouri": 0,
    "Akron": 0,
    "UCLA": 0,
    "Liberty": 0,
    "Montana": 0,
    "San Diego St.": 0,
    "St. Fran.-Pa.": 0,
    "Mt St Mary's": 0,
    "McNeese": 0,
    "Mich. St.": 1
}

ESPN_TO_PP_MAP = {
    "Alabama State Hornets": "Alabama St.",
    "Auburn Tigers": "Auburn",
    "Creighton Bluejays": "Creighton",
    "Louisville Cardinals": "Louisville",
    "UC San Diego Tritons": "UC San Diego",
    "Michigan Wolverines": "Michigan",
    "Yale Bulldogs": "Yale",
    "Texas A&M Aggies": "Texas A&M",
    "North Carolina Tar Heels": "North Carolina",
    "Ole Miss Rebels": "Ole Miss",
    "Lipscomb Bisons": "Lipscomb",
    "Iowa State Cyclones": "Iowa St.",
    "New Mexico Lobos": "New Mexico",
    "Marquette Golden Eagles": "Marquette",
    "Bryant Bulldogs": "Bryant",
    "Michigan State Spartans": "Mich. St.",
    "Baylor Bears": "Baylor",
    "Duke Blue Devils": "Duke",
    "BYU Cougars": "BYU",
    "Wisconsin Badgers": "Wisconsin",
    "Saint Mary's Gaels": "Saint Mary's",
    "Alabama Crimson Tide": "Alabama",
    "Mount St. Mary's Mountaineers": "Mt St Mary's",
    "Mississippi State Bulldogs": "Miss. St.",
    "Liberty Flames": "Liberty",
    "Oregon Ducks": "Oregon",
    "Akron Zips": "Akron",
    "Arizona Wildcats": "Arizona",
    "VCU Rams": "VCU",
    "Montana Grizzlies": "Montana",
    "Vanderbilt Commodores": "Vanderbilt",
    "Robert Morris Colonials": "Robert Morris",
    "Norfolk State Spartans": "Norfolk St.",
    "Florida Gators": "Florida",
    "Oklahoma Sooners": "Oklahoma",
    "UConn Huskies": "UConn",
    "Colorado State Rams": "Colo. St.",
    "Memphis Tigers": "Memphis",
    "Grand Canyon Lopes": "Grand Canyon",
    "Maryland Terrapins": "Maryland",
    "Drake Bulldogs": "Drake",
    "Missouri Tigers": "Missouri",
    "UNC Wilmington Seahawks": "UNCW",
    "Texas Tech Red Raiders": "Texas Tech",
    "Arkansas Razorbacks": "Arkansas",
    "Kansas Jayhawks": "Kansas",
    "Omaha Mavericks": "Omaha",
    "St. John's Red Storm": "St. John's",
    "Gonzaga Bulldogs": "Gonzaga",
    "Houston Cougars": "Houston",
    "McNeese Cowboys": "McNeese",
    "Purdue Boilermakers": "Purdue",
    "UCLA Bruins": "UCLA",
    "Tennessee Volunteers": "Tennessee",
    "SIU Edwardsville Cougars": "SIUE",
    "Georgia Bulldogs": "Georgia",
    "Clemson Tigers": "Clemson",
    "High Point Panthers": "High Point",
    "Xavier Musketeers": "Xavier",
    "Illinois Fighting Illini": "Illinois",
    "Troy Trojans": "Troy",
    "Kentucky Wildcats": "Kentucky",
    "Utah State Aggies": "Utah St.",
    "Wofford Terriers": "Wofford",
    "San Diego State Aztecs": "San Diego St.",
    "St. Francis (PA) Red Flash": "St. Fran.-Pa.",
    "American University Eagles": "American",
    "Texas Longhorns": "Texas"
}
